apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gvn-cpu-karpenter
spec:
  template:
    metadata:
      labels: 
        type: karpenter
        NodeGroupType: gvn-cpu-karpenter
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot","on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["xlarge", "2xlarge", "4xlarge", "8xlarge"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gvn-cpu-karpenter
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 100m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gvn-cpu-karpenter
spec:
  tags:
    KarpenterProvisionerName: "gvn-cpu-karpenter"
    NodeType: "cpu"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        encrypted: true
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 300Gi
        volumeType: gp3
        encrypted: true
  role: "KarpenterNodeRole-dify-eks" # replace with your cluster name
  amiSelectorTerms:
    - alias: "al2023@v20250228"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "dify-eks" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "dify-eks" # replace with your cluster name